/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PropertyUsersRouteImport } from './routes/property-users'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyUsersRoute = PropertyUsersRouteImport.update({
  id: '/property-users',
  path: '/property-users',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property-users': typeof PropertyUsersRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property-users': typeof PropertyUsersRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property-users': typeof PropertyUsersRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/profile'
    | '/properties'
    | '/property-users'
    | '/settings'
    | '/tenants'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/profile'
    | '/properties'
    | '/property-users'
    | '/settings'
    | '/tenants'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/profile'
    | '/properties'
    | '/property-users'
    | '/settings'
    | '/tenants'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRoute
  PropertyUsersRoute: typeof PropertyUsersRoute
  SettingsRoute: typeof SettingsRoute
  TenantsRoute: typeof TenantsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-users': {
      id: '/property-users'
      path: '/property-users'
      fullPath: '/property-users'
      preLoaderRoute: typeof PropertyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRoute,
  PropertyUsersRoute: PropertyUsersRoute,
  SettingsRoute: SettingsRoute,
  TenantsRoute: TenantsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
